// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:ca9bd755-423c-46bf-9e82-d3663ca9f5b2",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_HM9ITfwZ3",
    "aws_user_pools_web_client_id": "4n9lpr6r6lcokbp6hoopgprgo4"
};


export default awsmobile;
